spring:
  datasource:
    url: jdbc:mysql://localhost:3306/certdb
    username: root
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
